// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt7MzZW-uc-NQLs1f9_Dr5moOVDpdJrbU',
    appId: '1:383707386307:web:0f7645d76980fb76d96d76',
    messagingSenderId: '383707386307',
    projectId: 'external-417c6',
    authDomain: 'external-417c6.firebaseapp.com',
    storageBucket: 'external-417c6.firebasestorage.app',
    measurementId: 'G-FDKL527CKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOMTRU1RAhXxlC1mx3_jELEVFqzOut7c8',
    appId: '1:383707386307:android:02a66d6e512e31c7d96d76',
    messagingSenderId: '383707386307',
    projectId: 'external-417c6',
    storageBucket: 'external-417c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC8LlLHuBjoyBw2CAFeQharf4lMWcQf2I',
    appId: '1:383707386307:ios:7f92dcabca428e9dd96d76',
    messagingSenderId: '383707386307',
    projectId: 'external-417c6',
    storageBucket: 'external-417c6.firebasestorage.app',
    iosBundleId: 'com.antigravity.mealplanner.smartMealPlanner',
  );
}
